version: '3.3'

networks:
  aw-network:
   driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
     - aw-network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks:
     - aw-network
    ports:
      - "3000:3000"

  